# -*- coding: utf-8 -*-
"""Atividade_2_Logica_Programacao_Francisco_Rayol.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pJ48L8NWiCwtBCoOxIXXHFx5Y_io3rNY

#Atividade Avaliativa 2 (Lógica de Programação)
"""

# Você irá jogar um pequeno jogo de 'loteria customizável' em Python.
# AS REGRAS ESTÃO A SEGUIR: Você escolherá o primeiro e o último número,
# gerando o range do sorteio. A diferença entre esses dois números deve ser de
# no mínimo 10. Por exemplo, selecionando o primeiro número 1, o último deve
# ser 11 no mínimo. Após definir o 'range' dos números do sorteio, escolha o
# seu número da aposta. Seu número deve estar dentro do 'range' previamente
# definido. Se o número sorteado for o seu escolhido, você venceu!

import random
#---
numeros_range = []
#---
jogar_novamente = True
maior_que_zero = False
maior_dez_unidades = False
dentro_do_range = False
resposta_opcoes = False
#---
def reset_conditions():
  global numeros_range, jogar_novamente, maior_que_zero
  numeros_range = []
  jogar_novamente = True
  maior_que_zero = False
#---
while jogar_novamente:
  while not maior_que_zero:
    numero_inicial = int(input('Digite o primeiro número do range do sorteio. Ele deve ser maior que zero: '))
    if numero_inicial > 0:
      maior_que_zero = True
      print("\nObrigado. Agora escolha o último número do range do sorteio\nObs: Este deve ser maior que o primeiro no mínimo dez unidades.\n")
      maior_dez_unidades = False
    else:
      print("Você não escolheu um número acima de zero.\n")
#---
  while not maior_dez_unidades:
    numero_final = int(input('Digite o último número do range do sorteio: '))
    if numero_final - numero_inicial >= 10 and numero_final > 0:
      maior_dez_unidades = True
      for i in range(numero_inicial, numero_final+1):
        numeros_range.append(i)
      print("\nObrigado. Agora escolha o número no qual você deseja apostar. Ele deve ser um dos números abaixo.")
      print(f"Esses são os números que participarão do sorteio: {numeros_range}")
      dentro_do_range = False
    else:
      if numero_final <= 0:
        print("\nVocê não escolheu um número acima de zero.")
      print("A diferença entre o primeiro e o último número não foi igual ou maior que dez.\n")
  #---
    while not dentro_do_range and maior_dez_unidades:
      numero_apostado = int(input('\nDigite o número que você deseja apostar: '))
      if numero_apostado in numeros_range:
        dentro_do_range = True
        numero_sorteado = random.choice(numeros_range)
        acertou = numero_apostado == numero_sorteado
        mensagem = f"\nSeu número apostado foi {numero_apostado} e o número sorteado foi {numero_sorteado}. Parabéns, você acertou!" if acertou else f"\nO número sorteado foi {numero_sorteado}, porém o seu número apostado foi {numero_apostado}. Mais sorte na próxima tentativa!"
        print(mensagem)
        if not acertou:
          resposta_opcoes = False
          while not resposta_opcoes:
            resposta_jogar = input("\nDeseja apostar novamente?\nDigite sim ou não: ")
            if resposta_jogar == "sim":
              print("\nTudo bem! Vamos jogar novamente.\n")
              resposta_opcoes = True
              #---
              reset_conditions()
              #---
            elif resposta_jogar == "não" or resposta_jogar == "nao":
              print("\nObrigado por jogar!")
              jogar_novamente = False
              resposta_opcoes = True
            else:
              print("\nPor favor, digite sim ou não.")
        else:
            jogar_novamente = False
      #---
      else:
        print("O número apostado não está dentro do range do sorteio.\n")
#----

